apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: itpy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: itpy
    app.kubernetes.io/part-of: byoc-app-bnra
  name: itpy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: itpy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: itpy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-otep-tenant/byoc-app-bnra/itpy@sha256:73c99091db1b6b77ed46064388a219de5746881e1d667328364481a13d268db8
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
