apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: itpy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: itpy
    app.kubernetes.io/part-of: byoc-app-bnra
  name: itpy
spec:
  rules:
  - host: itpy-byoc-otep-tenant.apps.fbea785b1004af8d5c54.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: itpy
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
